services:
  - type: web
    name: negocio-eros-de-nuit-api
    runtime: docker
    plan: free
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
